### ISSUE TITLE
how can I enable data persistence?

### ISSUE THREAD

**Issue by uebmaster** [senaite/senaite.docker#15]
I have run the container, but stopping it loses the data.

How can I make the data persist even after the container is restarted?

Is it possible to do it in production as well?

Thanks.

PD: Sorry for my bad english.

**Comment by ramonski** [comment]
Hi @uebmaster,

please ask such questions in the community forum:
https://community.senaite.org

However, you can use a docker compose file like this to mount the database outside the container: https://github.com/senaite/senaite.docker/issues/12#issuecomment-1207278441
