### ISSUE TITLE
docker-compose up error: senaite-latest, repository does not exist ...

### ISSUE THREAD

**Issue by cleary** [senaite/senaite.docker#16]
`docker-compose up` throws an error:
```
Error response from daemon: pull access denied for senaite-latest, repository does not exist or may require 'docker login'
```

changing `senaite-latest` to `senaite/senaite:edge` got it running for me

**Comment by ramonski** [comment]
Hi @cleary,
There are either the tags `2.x` or `edge` available in the official Docker repository:
https://hub.docker.com/r/senaite/senaite/tags

While they are currently both the same, the first is meant to give the latest version of the `2.x` version branch, while the latter might give you also the latest `3.x` versions (when they become available;))
Please change your docker compose file accordingly, Thanks
