### ISSUE TITLE
Start docker container with multiple addons

### ISSUE THREAD

**Issue by veritiegroup** [senaite/senaite.docker#22]
It doesn't seem to be possible to define more than one addon with the ADDONS environment variable.

I have tried, for example
`... -e ADDONS="senaite.storage,senaite.patient"`
`... -e ADDONS="senaite.storage;senaite.patient"`
`... -e ADDONS="senaite.storage\nsenaite.patient"`

But none of these work. Is this currently possible?

**Comment by ramonski** [comment]
Please use spaces instead, e.g. `-e ADDONS="senaite.storage senaite.patient"`

**Comment by veritiegroup** [comment]
Ah, spaces! Didn't try that. Great thank you!
