### ISSUE TITLE
Remove healthchecks from Dockerfiles

### ISSUE THREAD

**Issue by SuperSandro2000** [senaite/senaite.docker#4]
The healthchecks increase the startup time of the containers by one minute if the first check fails which likely happens. Also they only check if the webserver is available which does not mean the application is healthy or working at all.

Also see the FAQ of the official Docker library https://github.com/docker-library/faq#healthcheck.

**Comment by ramonski** [comment]
Healthchecks are removed for the latest builds:
https://hub.docker.com/repository/docker/senaite/senaite
Thanks!
