### ISSUE TITLE
EXPOSE in a Dockerfile does not publish a port

### ISSUE THREAD

**Issue by SuperSandro2000** [senaite/senaite.docker#5]
> This image exposes the TCP Port 8080 via EXPOSE 8080, so standard container linking will make it automatically available to the linked containers.

According to the Docker Docs https://docs.docker.com/engine/reference/builder/#expose this is not true. Also the page about legacy linking https://docs.docker.com/network/links/ does not mention that expose works like this.

**Comment by ramonski** [comment]
Updated the documentation in https://github.com/senaite/senaite.docker/commit/c4308fa8267fb738d0fb315f53827e9a26c0ad72
