### ISSUE TITLE
zc.buildout failing on docker build

### ISSUE THREAD

**Issue by Givo29** [senaite/senaite.docker#6]
**Bug Description:**
The build is unable to find the `zc.buildout` files, possibly caused by `ez_setup` deprecation?

**Versions Affected:**
- 1.3.3
- 1.3.4

**To Reproduce:**
As per the documentation:
```
$ git clone https://github.com/senaite/senaite.docker
$ cd senaite.docker/<version>
$ docker build -t senaite .
$ docker run --rm --name senaite -p 8080:8080 senaite
```

**Screenshots:**
![image](https://user-images.githubusercontent.com/21019692/123210051-cf556e00-d504-11eb-8d5a-b9f0abd9bd2f.png)

**Comment by samimis97** [comment]
I am getting the same issue... how to resolve ?

**Comment by SingingDwarf** [comment]
Likewise, I get the same

**Comment by ramonski** [comment]
Versions < 2.x are no longer maintained.

Please use the latest build which known to be working:
https://github.com/senaite/senaite.core/actions/workflows/docker.yml
