### ISSUE TITLE
Unable to add senaite.health as addon

### ISSUE THREAD

**Issue by sbganesh** [senaite/senaite.docker#8]
Hi ,

I wanted to add the senaite.health as addon , but after making the changes in the buildout.cfg  when ran the 
sudo docker build -t senaite .

Version and requirements information containing senaite.lims:
  [versions] constraint on senaite.lims: 2.1.0
  Base installation request: 'Plone', 'senaite.lims', 'senaite.health', 'plone.recipe.zope2instance'
  Requirement of senaite.health: senaite.lims<1.4.0
  Requirement of senaite.health: senaite.lims>=1.3.5
  Requirement of senaite.lims==2.1.0: setuptools
  Requirement of senaite.lims==2.1.0: senaite.jsonapi==2.1.0
  Requirement of senaite.lims==2.1.0: senaite.impress==2.1.0
  Requirement of senaite.lims==2.1.0: senaite.app.supermodel==2.1.0
  Requirement of senaite.lims==2.1.0: senaite.app.spotlight==2.1.0
  Requirement of senaite.lims==2.1.0: senaite.app.listing==2.1.0
  Requirement of senaite.lims==2.1.0: senaite.core==2.1.0
  Requirement of senaite.lims==2.1.0: Plone==5.2.6
  Requirement of senaite.panic<1.2.0: senaite.lims>=1.3.4
While:
  Installing instance.
Error: The requirement ('senaite.lims<1.4.0') is not allowed by your [versions] constraint (2.1.0)

====
buildout.cfg ( version 2.1.0) i just added the seanite.health to the egg.

eggs +=
    senaite.lims
    senaite.health

**Comment by ramonski** [comment]
Hi @sbganesh,
`senaite.health` is discontinued for Senaite 2.x.
You might want to use the `senaite.patient` add-on instead.
